NumPY Array

In [3]:
import numpy as np
a = np.array([1,2,3])
print(a)
type(a)
print(a.ndim)

[1 2 3]
1


In [14]:
# Two dimensional Arrays
b= np.array([[1,2,3],[3,4,5]])
print(b)

[[1 2 3]
 [3 4 5]]


Attributes of ndarray

In [6]:
b.shape

(2, 3)

In [9]:
a.dtype

dtype('int32')

In [9]:
a.size

3

In [10]:
#The size of bytes of each element of an array can be found as 
a.itemsize

4

In [12]:
np.square(a)

array([1, 4, 9], dtype=int32)

In [15]:
np.add(a,b)

array([[2, 4, 6],
       [4, 6, 8]])

In [16]:
np.sqrt(a)

array([1.        , 1.41421356, 1.73205081])

In [17]:
np.exp(a)

array([ 2.71828183,  7.3890561 , 20.08553692])

In [11]:
# The buffer containing actual element of an arrays can be found by
a.data

In [10]:
c=np.array([2.1,2.2,2.3])
c.dtype

dtype('float64')

Information about Different Funcions

In [88]:
np.info(np.array_split)

 array_split(ary, indices_or_sections, axis=0)

Split an array into multiple sub-arrays.

Please refer to the ``split`` documentation.  The only difference
between these functions is that ``array_split`` allows
`indices_or_sections` to be an integer that does *not* equally
divide the axis. For an array of length l that should be split
into n sections, it returns l % n sub-arrays of size l//n + 1
and the rest of size l//n.

See Also
--------
split : Split array into multiple sub-arrays of equal size.

Examples
--------
>>> x = np.arange(8.0)
>>> np.array_split(x, 3)
    [array([ 0.,  1.,  2.]), array([ 3.,  4.,  5.]), array([ 6.,  7.])]

>>> x = np.arange(7.0)
>>> np.array_split(x, 3)
    [array([ 0.,  1.,  2.]), array([ 3.,  4.]), array([ 5.,  6.])]


Different Ways for Array creation 

In [75]:
e=np.arange(6)
e

array([0, 1, 2, 3, 4, 5])

In [114]:
d= np.zeros((2,3))
print(d)

[[0. 0. 0.]
 [0. 0. 0.]]


In [13]:
e=np.ones((2,4))
print(e)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [14]:
f= np.random.rand(2,3)
print(f)

[[0.60503306 0.76310046 0.00231231]
 [0.59779601 0.66902283 0.87024464]]


In [98]:
G5 = np.eye(6)
print(G5)
G= np.array([[2,4],[3,5]])
G6 = np.diagonal(G)
print(G6)

[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]
[2 5]


In [35]:
# you can also use get unique values from an array as well

a = np.array([11,22,3,4,1,5,6,11,22,3,7])
uniques= np.unique(a)
# you can also get counts as well 
# you can also get unique rows as well by using return_index=True
uniques,counts,unique_rows = np.unique(a, axis=0, return_index=True,return_counts=True)
print(a)
print(counts)
print(uniques)
print(unique_rows)

[11 22  3  4  1  5  6 11 22  3  7]
[ 4  2  3  5  6 10  0  1]
[ 1  3  4  5  6  7 11 22]
[1 2 1 1 1 1 2 2]


Array Manipulation

In [81]:
op=np.insert(a,0,4)
op

array([ 4, 11, 22,  3,  4,  1,  5,  6, 11, 22,  3,  7])

In [87]:
# combining an array
x=np.array([1,2])
y=np.array([3,5])
concated_array = np.concatenate((x,y),axis=0)
concated_array

array([1, 2, 3, 5])

In [89]:
z3 = np.split(concated_array,2)
z3

[array([1, 2]), array([3, 5])]

Rearranging Arrays

In [41]:
# Now we can use a transpose function as  well
a.transpose()

array([11, 22,  3,  4,  1,  5,  6, 11, 22,  3,  7])

In [48]:
# You can also reverse an arrayi.e elements of the array using flip
np.flip(a)
# You can also reverse a multidimensional array as well
new1 = np.array([[3,4],[5,6]])
np.flip(new1)
# you can also flip row or column by using axis = 0 for rows and axis=1 for columns
print(new1)
z=np.flip(new1, axis=1)
print(z)

[[3 4]
 [5 6]]
[[4 3]
 [6 5]]


In [21]:
# we can also generate an array by using arange by using the three arguments startpoint,endpoint,increment
g= np.arange(1,20,2)

print(g)
g

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [23]:
# to generate an array of floats we can linspace function wiht parameteres starting and ending points as first two 
# arguments but the last argument will be total items we want in an array this will genertae random number from first
# two arguments
i = np.linspace(1,2,20)
print(i)

[1.         1.05263158 1.10526316 1.15789474 1.21052632 1.26315789
 1.31578947 1.36842105 1.42105263 1.47368421 1.52631579 1.57894737
 1.63157895 1.68421053 1.73684211 1.78947368 1.84210526 1.89473684
 1.94736842 2.        ]


In [4]:
#we can view the diemension of an array using numpy shape
A = np.array([[1,2],[3,4]])
A.shape

(2, 2)

In [ ]:
# numpy array also have aggregate functions as well 
print (C.min())
print(C.max())
print(C.mean())
print(C.sum())

Reshapping and Flatening of an Array

In [6]:
# we can reshape an array by using the reshape() function of numpy
K = np.arange(1,16,1).reshape(3,5)
K

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [55]:
# One can use flatten and ravel for the purpose of flatening a multidimensional array
multi = np.array([[1,3],[5,6]])
print(multi)
multi.flatten()
# flatten does not change the parent array
# but it does not happen with ravel
x = multi.ravel()
print(x)
x[1]
# as you can see this has affected the parent array 

[[1 3]
 [5 6]]
[1 3 5 6]


3

In [ ]:
Other Mathematic related Functions

In [56]:
x=np.power(100,8)
x

1874919424

In [61]:
# return an array of specified dimesnions without initalizing entries
z = np.empty((2,4),dtype=int)
z

array([[-884167928,        363,    6357101,    7077996],
       [   6488175,    6553646,    7077996,          0]])

In [ ]:
# The dot product of two arrays can ve found by using the dot()
x=np.array([[1,2],[4,5]])
y=np.array([[3,5],[1,4]])

z=x.dot(y)
print(z)

In [99]:
res=np.add(x,y)
res

array([4, 7])

In [101]:
res=np.subtract(x,y)
res

array([-2, -3])

In [102]:
res = np.multiply(x,y)
res

array([ 3, 10])

In [105]:
res =np.multiply(x,y)
res

array([ 3, 10])

In [107]:
res =np.remainder(x,y)
res

array([1, 2], dtype=int32)

In [108]:
res = np.array_equal(x,y)
res

False

Trignometric functions on arrays

In [64]:
z=np.array([[3,4,1,5],[2,4,5,6]])
res1=np.sin(z)
res2=np.cos(z)
res3=np.tan(z)

array([[-0.14254654,  1.15782128,  1.55740772, -3.38051501],
       [-2.18503986,  1.15782128, -3.38051501, -0.29100619]])

Numpy and Statistics

In [111]:
# variacne
res = np.var(x)
res

0.25

In [113]:
# standard Deviation
res =np.std(x)
res

0.5